# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='new_wish_field',
            field=models.BooleanField(default=False),
        ),
    ]
